### ISSUE TITLE
Flattop breaks syntax highlighning

### ISSUE THREAD

**Issue by ccrvlh** [ostranme/swagger-ui-themes#45]
Would be great to keep the JSON highlighting.

Looks like it's this block:

```css
.swagger-ui .opblock-body pre span {
  color: #fff !important;
}
```
